version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/usr/share/nginx/html:ro
            - ./api/nginx/site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7-fpm
        volumes:
            - .:/usr/share/nginx/html
    composer:
        image: composer/composer:php7
        command: install --ignore-platform-reqs
        volumes:
            - .:/app